import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "next-themes";
import { NextStepProvider, NextStep } from "nextstepjs";
import ClientOnly from "../components/ClientOnly";
import ReduxProvider from "@/components/ReduxProvider";
import GlobalOverlay from "@/components/GlobalOverlay";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const steps = [
  {
    tour: "firsttour",
    steps: [
      {
        icon: <>👋</>,
        title: "Tour 1, Step 1",
        content: <>First tour, first step</>,
        selector: "#tour1-step1",
        side: "left",
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 10,
      },
      {
        icon: <>🎉</>,
        title: "Tour 1, Step 2",
        content: <>First tour, second step</>,
        selector: "#tour1-step2",
        side: "left",
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 10,
      },
    ],
  },
];

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider disableTransitionOnChange>
          <ClientOnly>
            <ReduxProvider>
              <NextStepProvider>
                <NextStep steps={steps}>
                  <Navbar />
                  {children}
                  <GlobalOverlay />
                </NextStep>
              </NextStepProvider>
            </ReduxProvider>
          </ClientOnly>
        </ThemeProvider>
      </body>
    </html>
  );
}
